name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Log in to GitHub Packages
      - name: Log in to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/thermoflask:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/thermoflask:latest ghcr.io/${{ github.repository_owner }}/thermoflask:latest

      # Push to Docker Hub
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/thermoflask:latest

      # Push to GitHub Packages
      - name: Push to GitHub Packages
        run: docker push ghcr.io/${{ github.repository_owner }}/thermoflask:latest
        